apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dockyards-talos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dockyards-talos
subjects:
- kind: ServiceAccount
  name: dockyards-talos
