//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha3

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *LinkConfig) DeepCopyInto(out *LinkConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *LinkConfig) DeepCopy() *LinkConfig {
	if in == nil {
		return nil
	}
	out := new(LinkConfig)
	in.DeepCopyInto(out)

	return out
}

func (in *LinkConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}

	return nil
}

func (in *LinkConfigDefaultRoute) DeepCopyInto(out *LinkConfigDefaultRoute) {
	*out = *in
}

func (in *LinkConfigDefaultRoute) DeepCopy() *LinkConfigDefaultRoute {
	if in == nil {
		return nil
	}
	out := new(LinkConfigDefaultRoute)
	in.DeepCopyInto(out)

	return out
}

func (in *LinkConfigList) DeepCopyInto(out *LinkConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LinkConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *LinkConfigList) DeepCopy() *LinkConfigList {
	if in == nil {
		return nil
	}
	out := new(LinkConfigList)
	in.DeepCopyInto(out)

	return out
}

func (in *LinkConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}

	return nil
}

func (in *LinkConfigNode) DeepCopyInto(out *LinkConfigNode) {
	*out = *in
}

func (in *LinkConfigNode) DeepCopy() *LinkConfigNode {
	if in == nil {
		return nil
	}
	out := new(LinkConfigNode)
	in.DeepCopyInto(out)

	return out
}

func (in *LinkConfigRoute) DeepCopyInto(out *LinkConfigRoute) {
	*out = *in
}

func (in *LinkConfigRoute) DeepCopy() *LinkConfigRoute {
	if in == nil {
		return nil
	}
	out := new(LinkConfigRoute)
	in.DeepCopyInto(out)

	return out
}
